version: '3'

services:

  frame-service:
    build:
      context: ./frame
      dockerfile: Dockerfile
    ports:
      - "5000:5000/udp"
    networks:
      - ntw
    depends_on:
      - rabbitmq
      - insightface-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9092
      KAFKA_TOPIC: my-topic
    volumes:
      - ./broker:/app/broker


  insightface-service:
    build:
      context: ./insight_face
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ntw

  worker-service:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "65432:65432/tcp"
    environment:
      - WEBSOCKET_PORT=8765
    depends_on:
      - insightface-service  
    networks:
      - ntw
    volumes:
      - ./broker:/app/broker

  faiss-service:
    build:
      context: ./faiss-db
      dockerfile: Dockerfile
    depends_on:
      - insightface-service
      - rabbitmq
    networks:
      - ntw
    volumes:
      - ./broker:/app/broker

  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ntw
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "rabbitmq", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ntw
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ntw
      
networks:
  ntw:
    name: ntw
    driver: bridge

volumes:
  rabbitmq-data: