version: '3'

services:

  frame-service:
    build:
      context: ./frame
      dockerfile: Dockerfile
    ports:
      - "5000:5000/udp"
    networks:
      - ntw
    depends_on:
      - rabbitmq
      - insightface-service
    volumes:
      - ./broker:/app/broker


  insightface-service:
    build:
      context: ./insight_face
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ntw

  worker-service:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - insightface-service  
    networks:
      - ntw
    ports:
      - "8080:8080"
    volumes:
      - ./broker:/app/broker

  faiss-service:
    build:
      context: ./faiss-db
      dockerfile: Dockerfile
    depends_on:
      - insightface-service
      - rabbitmq
    networks:
      - ntw
    volumes:
      - ./broker:/app/broker

  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ntw
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ntw
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ntw

networks:
  ntw:
    name: ntw
    driver: bridge
    external: true

volumes:
  rabbitmq-data:
  