version: '3'

services:

  frame-service:
    build:
      context: ./frame
      dockerfile: Dockerfile
    ports:
      - "5000:5000/udp"
    networks:
      - ntw
    depends_on:
      - rabbitmq
      - insightface-service
    command: python frame.py


  insightface-service:
    build:
      context: ./insight_face
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - ntw

  
  worker-service:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - insightface-service
    networks:
      - ntw

  faiss-service:
    build:
      context: ./faiss-db
      dockerfile: Dockerfile
    depends_on:
      - insightface-service
      - rabbitmq
    networks:
      - ntw


  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ntw
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

      
networks:
  ntw:
    name: ntw
    driver: bridge

volumes:
  rabbitmq-data: